<?php

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 */
function asc_install() {
  include_once DRUPAL_ROOT . '/profiles/minimal/minimal.install';
  $disable = array(
    'toolbar',
    'dblog',
  
);
  module_disable($disable,TRUE);

  minimal_install();

  // Update admin username and e-mail.
  db_update('users')
    ->fields(array('name' => 'ascoverseer','mail' => 'asctech@osu.edu'))
    ->condition('uid', '1')
    ->execute();
}



