; This file was auto-generated by drush_make
core = 7.x

api = 2

; Modules
projects[acl][subdir] = "profiles/asc/modules/contrib/acl"
projects[acl][version] = "1.0"

projects[addressfield][subdir] = "profiles/asc/modules/contrib/addressfield"
projects[addressfield][version] = "1.0-beta5"

projects[admin][subdir] = "profiles/asc/modules/contrib/admin"
projects[admin][version] = "2.0-beta3"

projects[asc_auth][download][type] = "git"
projects[asc_auth][download][url] = "git@code.osu.edu:asctech/asc_auth.git"
projects[asc_auth][download][branch] = "7.x-1.x"
projects[asc_auth][type] = "module"
projects[asc_auth][subdir] = "profiles/asc/modules/features/asc_auth"
projects[asc_auth][version] = "1.1"

projects[asc_blog][download][type] = "git"
projects[asc_blog][download][url] = "https://github.com/ASCTech/asc_blog.git"
projects[asc_blog][download][branch] = "7.x-1.0"
projects[asc_blog][type] = "module"
projects[asc_blog][subdir] = "profiles/asc/modules/features/asc_blog"
projects[asc_blog][version] = "1.0"

projects[asc_footer][download][type] = "git"
projects[asc_footer][download][url] = "https://github.com/ASCTech/asc_footer.git"
projects[asc_footer][download][branch] = "7.x-1.0"
projects[asc_footer][download][subdir] = "profiles/asc/modules/custom/asc_footer"
projects[asc_footer][type] = "module"

projects[asc_commerce][download][type] = "git"
projects[asc_commerce][download][url] = "https://github.com/ASCTech/asc_commerce.git"
projects[asc_commerce][download][branch] = "master"
projects[asc_commerce][type] = "module"
projects[asc_commerce][subdir] = "profiles/asc/modules/features/asc_commerce"
projects[asc_commerce][version] = "1.0"

projects[asc_events][download][type] = "git"
projects[asc_events][download][url] = "https://github.com/ASCTech/asc_events.git"
projects[asc_events][download][branch] = "7.x-1.x"
projects[asc_events][type] = "module"
projects[asc_events][subdir] = "profiles/asc/modules/features/asc_events"
projects[asc_events][version] = "1.0"

projects[asc_front][download][type] = "git"
projects[asc_front][download][url] = "https://github.com/ASCTech/asc_front.git"
projects[asc_front][download][branch] = "7.x-1.x"
projects[asc_front][type] = "module"
projects[asc_front][subdir] = "profiles/asc/modules/features/asc_front"

projects[asc_image_handling][download][type] = "git"
projects[asc_image_handling][download][url] = "https://github.com/ASCTech/asc_image_handling.git"
projects[asc_image_handling][download][branch] = "7.x-1.2"
projects[asc_image_handling][type] = "module"
projects[asc_image_handling][subdir] = "profiles/asc/modules/features/asc_image_handling"
projects[asc_image_handling][version] = "1.2"

projects[asc_kmdata][download][type] = "git"
projects[asc_kmdata][download][url] = "https://github.com/ASCTech/asc_kmdata.git"
projects[asc_kmdata][download][branch] = "master"
projects[asc_kmdata][type] = "module"
projects[asc_kmdata][subdir] = "profiles/asc/modules/features/asc_kmdata"
projects[asc_kmdata][version] = "1.0-beta1"

projects[asc_menu_block][download][type] = "git"
projects[asc_menu_block][download][url] = "https://github.com/ASCTech/asc_menu_block.git"
projects[asc_menu_block][download][branch] = "7.x-1.x"
projects[asc_menu_block][type] = "module"
projects[asc_menu_block][subdir] = "profiles/asc/modules/custom/asc_menu_block"
projects[asc_menu_block][version] = "1.0"

projects[asc_microsites][download][type] = "git"
projects[asc_microsites][download][url] = "https://github.com/ASCTech/asc_microsites.git"
projects[asc_microsites][download][branch] = "7.x-1.0"
projects[asc_microsites][type] = "module"
projects[asc_microsites][subdir] = "profiles/asc/modules/features/asc_microsites"
projects[asc_microsites][version] = "1.0-dev"

projects[asc_news][download][type] = "git"
projects[asc_news][download][url] = "https://github.com/ASCTech/asc_news.git"
projects[asc_news][download][branch] = "7.x-1.0"
projects[asc_news][type] = "module"
projects[asc_news][subdir] = "profiles/asc/modules/features/asc_news"
projects[asc_news][version] = "1.0"

projects[asc_people][download][type] = "git"
projects[asc_people][download][url] = "https://github.com/ASCTech/asc_people.git"
projects[asc_people][download][branch] = "7.x-1.2"
projects[asc_people][type] = "module"
projects[asc_people][subdir] = "profiles/asc/modules/features/asc_people"
projects[asc_people][version] = "1.2"

projects[asc_rss][download][type] = "git"
projects[asc_rss][download][url] = "https://github.com/ASCTech/asc_rss.git"
projects[asc_rss][download][branch] = "7.x-1.0"
projects[asc_rss][type] = "module"
projects[asc_rss][subdir] = "profiles/asc/modules/features/asc_rss"
projects[asc_rss][version] = "1.0"

projects[asc_webforms][download][type] = "git"
projects[asc_webforms][download][url] = "https://github.com/ASCTech/asc_webforms.git"
projects[asc_webforms][download][branch] = "7.x-1.0"
projects[asc_webforms][type] = "module"
projects[asc_webforms][subdir] = "profiles/asc/modules/features/asc_webforms"
projects[asc_webforms][version] = "1.0"

projects[auto_nodetitle][subdir] = "profiles/asc/modules/contrib/auto_nodetitle"
projects[auto_nodetitle][version] = "1.0"

projects[better_exposed_filters][subdir] = "profiles/asc/modules/contrib/better_exposed_filters"
projects[better_exposed_filters][version] = "3.0-beta4"

projects[block_class][subdir] = "profiles/asc/modules/contrib/block_class"
projects[block_class][version] = "2.1"

projects[block_titlelink][subdir] = "profiles/asc/modules/contrib/block_titlelink"
projects[block_titlelink][version] = "1.3"

projects[ctools][subdir] = "profiles/asc/modules/contrib/ctools"
projects[ctools][version] = "1.4"

projects[calendar][subdir] = "profiles/asc/modules/contrib/calendar"
projects[calendar][version] = "3.4"

projects[captcha][subdir] = "profiles/asc/modules/contrib/captcha"
projects[captcha][version] = "1.1"

projects[node_clone][subdir] = "profiles/asc/modules/contrib/node_clone"
projects[node_clone][version] = "1.0-rc2"

projects[color_field][subdir] = "profiles/asc/modules/contrib/color_field"
projects[color_field][version] = "1.6"

projects[commerce][subdir] = "profiles/asc/modules/contrib/commerce"
projects[commerce][version] = "1.9"

projects[context][subdir] = "profiles/asc/modules/contrib/context"
projects[context][version] = "3.2"

projects[date][subdir] = "profiles/asc/modules/contrib/date"
projects[date][version] = "2.7"

projects[ds][subdir] = "profiles/asc/modules/contrib/ds"
projects[ds][version] = "2.6"

projects[email][subdir] = "profiles/asc/modules/contrib/email"
projects[email][version] = "1.3"

projects[entity][subdir] = "profiles/asc/modules/contrib/entity"
projects[entity][version] = "1.5"

projects[exclude_node_title][subdir] = "profiles/asc/modules/contrib/exclude_node_title"
projects[exclude_node_title][version] = "1.7"

projects[features_extra][subdir] = "profiles/asc/modules/contrib/features_extra"
projects[features_extra][version] = "1.0-beta1"

projects[features][subdir] = "profiles/asc/modules/contrib/features"
projects[features][version] = "2.0"

projects[field_group][subdir] = "profiles/asc/modules/contrib/field_group"
projects[field_group][version] = "1.3"

projects[file_entity][subdir] = "profiles/asc/modules/contrib/file_entity"
projects[file_entity][version] = "2.0-alpha3"

projects[form_builder][subdir] = "profiles/asc/modules/form_builder"
projects[form_builder][version] = "1.4"

projects[galleryformatter][download][type] = "git"
projects[galleryformatter][download][url] = "git@code.osu.edu:asctech/asc_galleryformatter.git"
projects[galleryformatter][download][branch] = "master"
projects[galleryformatter][subdir] = "profiles/asc/modules/custom/asc_galleryformatter"

projects[libraries][subdir] = "profiles/asc/modules/libraries"
projects[libraries][version] = "2.2"

projects[lightbox2][subdir] = "profiles/asc/modules/contrib/lightbox2"
projects[lightbox2][version] = "1.0-beta1"

projects[link][subdir] = "profiles/asc/modules/contrib/link"
projects[link][version] = "1.2"

projects[location][subdir] = "profiles/asc/modules/contrib/location"
projects[location][version] = "3.2"

projects[markdown][subdir] = "profiles/asc/modules/contrib/markdown"
projects[markdown][version] = "1.2"

projects[masquerade][subdir] = "profiles/asc/modules/contrib/masquerade"
projects[masquerade][version] = "1.0-rc7"

projects[mathjax][subdir] = "contrib"

projects[media][subdir] = "profiles/asc/modules/contrib/media"
projects[media][version] = "2.0-unstable7"

projects[media_vimeo][subdir] = "profiles/asc/modules/contrib/media_vimeo"
projects[media_vimeo][version] = "2.0"

projects[media_youtube][subdir] = "profiles/asc/modules/contrib/media_youtube"
projects[media_youtube][version] = "2.0-rc4"

projects[menu_block][subdir] = "profiles/asc/modules/contrib/menu_block"
projects[menu_block][version] = "2.3"

projects[node_export][subdir] = "profiles/asc/modules/contrib/node_export"
projects[node_export][version] = "3.0"

projects[options_element][subdir] = "profiles/asc/modules/contrib/options_element"
projects[options_element][version] = "1.12"

projects[pathauto][subdir] = "profiles/asc/modules/contrib/pathauto"
projects[pathauto][version] = "1.2"

projects[piwik_reports][subdir] = "profiles/asc/modules/contrib/piwik_reports"
projects[piwik_reports][version] = "3.0-rc1"

projects[recaptcha][subdir] = "profiles/asc/modules/contrib/recaptcha"
projects[recaptcha][version] = "1.11"

projects[rules][subdir] = "profiles/asc/modules/contrib/rules"
projects[rules][version] = "2.7"

projects[shib_auth][type] = "module"
projects[shib_auth][subdir] = "contrib"
projects[shib_auth][subdir] = "profiles/asc/modules/contrib/shib_auth"
projects[shib_auth][version] = "4.0"

projects[shib_provision][subdir] = "profiles/asc/modules/contrib/shib_provision"
projects[shib_provision][version] = "1.0-beta4"

projects[special_menu_items][subdir] = "profiles/asc/modules/contrib/special_menu_items"
projects[special_menu_items][version] = "2.0"

projects[strongarm][subdir] = "profiles/asc/modules/contrib/strongarm"
projects[strongarm][version] = "2.0"

projects[taxonomy_entity_index][subdir] = "profiles/asc/modules/contrib/taxonomy_entity_index"
projects[taxonomy_entity_index][version] = "1.0-beta7"

projects[token][subdir] = "profiles/asc/modules/token"
projects[token][version] = "1.5"

projects[uuid][subdir] = "profiles/asc/modules/contrib/uuid"
projects[uuid][version] = "1.0-alpha5"

projects[views][subdir] = "profiles/asc/modules/contrib/views"
projects[views][version] = "3.8"

projects[views_bulk_operations][subdir] = "contrib"

projects[webform][subdir] = "profiles/asc/modules/contrib/webform"
projects[webform][version] = "4.0-rc4"

projects[wysiwyg][subdir] = "profiles/asc/modules/contrib/wysiwyg"
projects[wysiwyg][version] = "2.2"

projects[wysiwyg_button_order][subdir] = "profiles/asc/modules/contrib/wysiwyg_button_order"
projects[wysiwyg_button_order][version] = "1.0-rc1"

; Themes
projects[omega][subdir] = "profiles/asc/themes/omega"
projects[omega][version] = "3.1"

projects[q7][download][type] = "git"
projects[q7][download][url] = "git@code.osu.edu:asc-drupal/q7.git"
projects[q7][download][branch] = "7.x-1.1"
projects[q7][type] = "theme"
projects[q7][subdir] = "profiles/asc/themes/q7"
projects[q7][version] = "unknown"

; Modules
projects[asc_breadcrumbs][download][type] = "git"
projects[asc_breadcrumbs][download][url] = "https://github.com/ASCTech/asc_breadcrumbs.git"
projects[asc_breadcrumbs][download][branch] = "7.x-1.x"
projects[asc_breadcrumbs][subdir] = "profiles/asc/modules/custom/asc_courses"
projects[asc_breadcrumbs][type] = "module"

projects[asc_courses][download][type] = "git"
projects[asc_courses][download][url] = "https://github.com/ASCTech/asc_courses.git"
projects[asc_courses][download][branch] = "master"
projects[asc_courses][subdir] = "profiles/asc/modules/custom/asc_courses"
projects[asc_courses][type] = "module"

projects[asc_login_override][download][type] = "git"
projects[asc_login_override][download][url] = "https://github.com/ASCTech/asc_login_override.git"
projects[asc_login_override][download][branch] = "7.x-1.x"
projects[asc_login_override][subdir] = "profiles/asc/modules/custom/asc_login_override"
projects[asc_login_override][type] = "module"

projects[asc_people_kmdata_importer][download][type] = "git"
projects[asc_people_kmdata_importer][download][url] = "https://github.com/ASCTech/asc_login_override.git"
projects[asc_people_kmdata_importer][download][branch] = "7.x-1.x"
projects[asc_people_kmdata_importer][subdir] = "profiles/asc/modules/custom/asc_people_kmdata_importer"
projects[asc_people_kmdata_importer][type] = "module"

projects[asc_scrollletter][download][type] = "git"
projects[asc_scrollletter][download][url] = "https://github.com/ASCTech/asc_scrollletter.git"
projects[asc_scrollletter][download][branch] = "7.x-1.0"
projects[asc_scrollletter][subdir] = "profiles/asc/modules/custom/asc_scrollletter"
projects[asc_scrollletter][type] = "module"

projects[asc_signup][type] = "module"
projects[asc_signup][subdir] = "custom"
projects[asc_signup][download][type] = "git"
projects[asc_signup][download][branch] = "7.x-1.0"
projects[asc_signup][patch][] = https://raw.github.com/ASCTech/drush_make/master/patches/signup_override_login_link.patch

projects[asc_socialmedia][type] = "module"
projects[asc_socialmedia][subdir] = "custom"
projects[asc_socialmedia][download][type] = "git"
projects[asc_socialmedia][download][url] = "https://github.com/ASCTech/asc_socialmedia.git"
projects[asc_socialmedia][download][branch] = "7.x-1.x"

projects[asc_taxonomy_filter][download][type] = "git"
projects[asc_taxonomy_filter][download][url] = "https://github.com/ASCTech/asc_taxonomy_filter.git"
projects[asc_taxonomy_filter][download][branch] = "7.x-1.1"
projects[asc_taxonomy_filter][subdir] = "profiles/asc/modules/custom/asc_taxonomy_filter"
projects[asc_taxonomy_filter][type] = "module"

projects[asc_users][download][type] = "git"
projects[asc_users][download][url] = "https://github.com/ASCTech/asc_users.git"
projects[asc_users][download][branch] = "7.x-1.0"
projects[asc_users][subdir] = "profiles/asc/modules/custom/asc_users"
projects[asc_users][type] = "module"

projects[commerce_cybersource_sasop][download][type] = "git"
projects[commerce_cybersource_sasop][download][url] = "git@code.osu.edu:asctech/asc_commerce_cybersource_sasop.git"
projects[commerce_cybersource_sasop][download][branch] = "master"
projects[commerce_cybersource_sasop][subdir] = "profiles/asc/modules/custom/asc_commerce_cybersource_sasop"
projects[commerce_cybersource_sasop][type] = "module"

projects[migrate_d6tod7][download][type] = "git"
projects[migrate_d6tod7][download][url] = "git@code.osu.edu:asctech/migrate_d6tod7.git"
projects[migrate_d6tod7][download][branch] = "master"
projects[migrate_d6tod7][subdir] = "profiles/asc/modules/custom/asc_migrate_d6tod7"
projects[migrate_d6tod7][type] = "module"

projects[opic][download][type] = "git"
projects[opic][download][url] = "https://github.com/ASCTech/drupal_opic.git"
projects[opic][download][branch] = "7.x-2.1"
projects[opic][subdir] = "profiles/asc/modules/custom/opic"
projects[opic][type] = "module"

projects[tabsnomore][download][type] = "git"
projects[tabsnomore][download][url] = "http://git.drupal.org/sandbox/onkeltem/1730244.git"
projects[tabsnomore][download][branch] = "master"
projects[tabsnomore][type] = "module"

projects[webform_submissions_acl][download][type] = "git"
projects[webform_submissions_acl][download][url] = "https://github.com/ASCTech/webform_submissions_acl.git"
projects[webform_submissions_acl][download][branch] = "7.x-1.x"
projects[webform_submissions_acl][type] = "module"

; Libraries
libraries[jquery_ui][download][type] = "get"
libraries[jquery_ui][download][url] = "http://jquery-ui.googlecode.com/files/jquery-ui-1.7.zip"
libraries[jquery_ui][directory_name] = "jquery.ui"
libraries[jquery_ui][destination] = "libraries"

libraries[ckeditor][download][type]= "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.4/ckeditor_3.4.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][destination] = "libraries"

